export const ActionTypes ={
    SET_MOVIES:"SET_MOVIES",    // GELEN FİLMLERİ STORA AKTARMAYA YARAYACAK
    SET_MOVIES_LOADİNG:"SET_MOVIES_LOADİNG", // GELEN FİLMLERİN YÜKLENME DURUMU
    SET_MOVIES_ERROR:"SET_MOVIES_ERROR", // GELEN FİLMLER YÜKLENİRKEN HATA OLABİLİR

    SET_GENRES:"SET_GENRES",  // 
    SET_GENRES_LOADİNG:"SET_GENRES_LOADİNG", // TÜRLERİN YÜKLEME AŞAMASININ STATE 
    SET_GENRES_ERROR:"SET_GENRES_ERROR", // TÜRLERİN YÜKLENME HATA AŞAMASININ STATE
    
    
}